const modules={
 siswa:{icon:'✍️',title:'Data Siswa / Anggota',sheet:'Data Siswa',start:6,end:254,primary:'C',recordCols:['B','C','G','H','O','P','Q'],recordLabels:['ID','Nama','Kelas','Program','Sabuk','Keanggotaan','Status Siswa'],intro:'Tambah dan perbarui biodata siswa/anggota. ID dan nomor urut mengikuti format database Excel.',fields:[
  {c:'C',l:'Nama Lengkap',req:1},{c:'D',l:'L/P',type:'select',ref:'gender',req:1},{c:'E',l:'Tempat Lahir'},{c:'F',l:'Tanggal Lahir',type:'date'},{c:'G',l:'Kelas',type:'select',ref:'kelas'},{c:'H',l:'Program Keahlian',type:'select',ref:'program'},{c:'I',l:'Alamat',type:'textarea',cls:'two'},{c:'J',l:'No. HP Siswa'},{c:'K',l:'Nama Orang Tua/Wali'},{c:'L',l:'No. HP Wali'},{c:'M',l:'Tahun Pengesahan',type:'number'},{c:'N',l:'Tahun Masuk',type:'number',req:1},{c:'O',l:'Tingkat/Sabuk',type:'select',ref:'belt'},{c:'P',l:'Status Keanggotaan',type:'select',ref:'memberStatus'},{c:'Q',l:'Status Siswa',type:'select',ref:'studentStatus'},{c:'R',l:'Nomor Sertifikat'},{c:'S',l:'Catatan',type:'textarea',cls:'two'},{c:'T',l:'Tanggal Pengesahan / Tempat',cls:'full'}]},
 pengurus:{icon:'🧑‍💼',title:'Data Pengurus',sheet:'Data Pengurus',start:6,end:505,primary:'C',recordCols:['B','C','E','H','I','J'],recordLabels:['ID','Nama','Jabatan','Mulai','Periode','Status'],intro:'Kelola database pengurus rayon. ID pengurus otomatis mengikuti template workbook.',fields:[
  {c:'C',l:'Nama Lengkap',req:1},{c:'D',l:'L/P',type:'select',ref:'gender'},{c:'E',l:'Jabatan',type:'select',ref:'position',req:1},{c:'F',l:'No. HP / WhatsApp'},{c:'G',l:'Alamat',type:'textarea',cls:'two'},{c:'H',l:'Tahun Mulai',type:'number'},{c:'I',l:'Periode Kepengurusan'},{c:'J',l:'Status Pengurus',type:'select',ref:'pengurusStatus'},{c:'K',l:'Catatan',type:'textarea',cls:'full'}]},
 alumni:{icon:'🎓',title:'Data Alumni',sheet:'Data Alumni',start:6,end:505,primary:'B',link:'student',recordCols:['B','C','E','F','G','H','K','N'],recordLabels:['ID','Nama','Program','Masuk','Lulus','Sabuk','Aktivitas','Kontak'],intro:'Pilih anggota/siswa untuk mengisi atau memperbarui data alumni.',fields:[
  {c:'G',l:'Tahun Lulus',type:'number'},{c:'I',l:'No. HP / WhatsApp'},{c:'J',l:'Alamat',type:'textarea',cls:'two'},{c:'K',l:'Aktivitas Alumni',type:'select',ref:'alumniActivity'},{c:'L',l:'Instansi / Perusahaan / Kampus / Usaha',cls:'two'},{c:'M',l:'Jabatan / Program Studi'},{c:'N',l:'Status Kontak',type:'select',ref:'alumniContact'},{c:'O',l:'Catatan',type:'textarea',cls:'full'}]},
 kehadiran:{icon:'📅',title:'Kehadiran Bulanan',sheet:'Kehadiran',start:4,end:193,primary:'B',link:'student',special:'attendance',recordCols:['B','C','D','HM','HN','HO','HP','HQ','HR'],recordLabels:['ID','Nama','Sabuk','Total Hadir','Sakit','Izin','Tanpa Ket.','DO/Keluar','% Total'],intro:'Pilih anggota dan bulan, lalu isi jumlah hadir/sakit/izin/tanpa keterangan. Data bulanan langsung masuk ke kolom bulan yang tepat.'},
 kenaikan:{icon:'🥋',title:'Kenaikan Tingkat',sheet:'Kenaikan Tingkat',start:6,end:504,primary:'C',link:'student',recordCols:['B','C','D','E','F','J','K','L'],recordLabels:['Tanggal','ID','Nama','Sebelum','Sesudah','Jumlah','Hasil','Penguji'],intro:'Catat ujian kenaikan tingkat. Jumlah nilai dan hasil lulus mengikuti rumus workbook.',fields:[
  {c:'B',l:'Tanggal Ujian',type:'date',req:1},{c:'E',l:'Tingkat Sebelum',type:'select',ref:'belt'},{c:'F',l:'Tingkat Sesudah',type:'select',ref:'belt',req:1},{c:'G',l:'Nilai Teori',type:'number',min:0,max:100},{c:'H',l:'Nilai Praktik',type:'number',min:0,max:100},{c:'I',l:'Nilai Wawancara',type:'number',min:0,max:100},{c:'L',l:'Penguji'},{c:'M',l:'No. Sertifikat / Catatan',cls:'two'}]},
 prestasi:{icon:'🏆',title:'Prestasi',sheet:'Prestasi',start:5,end:504,primary:'C',link:'student',recordCols:['B','C','D','E','F','G','H'],recordLabels:['Tanggal','ID','Nama','Kegiatan','Tingkat','Kategori','Prestasi'],intro:'Catat prestasi siswa/anggota pada kejuaraan atau kegiatan organisasi.',fields:[
  {c:'B',l:'Tanggal',type:'date'},{c:'E',l:'Nama Kegiatan / Kejuaraan',req:1},{c:'F',l:'Tingkat',type:'select',opts:['Sekolah','Kecamatan','Kabupaten','Provinsi','Nasional','Internasional']},{c:'G',l:'Kategori'},{c:'H',l:'Prestasi / Juara',req:1},{c:'I',l:'Penyelenggara / No. Sertifikat',cls:'two'},{c:'J',l:'Catatan',type:'textarea',cls:'full'}]},
 iuran:{icon:'💳',title:'Iuran / Pembayaran',sheet:'Iuran',start:5,end:504,primary:'C',link:'student',recordCols:['B','C','D','E','F','G','H','I'],recordLabels:['Tanggal','ID','Nama','Periode','Jenis','Nominal','Metode','Status'],intro:'Catat pembayaran anggota. Nama mengikuti ID anggota.',fields:[
  {c:'B',l:'Tanggal',type:'date',req:1},{c:'E',l:'Bulan / Periode',req:1},{c:'F',l:'Jenis Pembayaran',type:'select',ref:'paymentType',req:1},{c:'G',l:'Nominal (Rp)',type:'number',min:0,req:1},{c:'H',l:'Metode',type:'select',ref:'paymentMethod'},{c:'I',l:'Status',type:'select',ref:'paymentStatus'},{c:'J',l:'Keterangan',type:'textarea',cls:'full'}]},
 pelanggaran:{icon:'⚠️',title:'Pelanggaran',sheet:'Data Pelanggaran',start:6,end:505,primary:'C',link:'student',recordCols:['B','C','D','E','F','G','I','J'],recordLabels:['Tanggal','ID','Nama','Jenis','Tingkat','Poin','Status','PJ'],intro:'Catat pelanggaran, poin, sanksi, dan status penyelesaian.',fields:[
  {c:'B',l:'Tanggal',type:'date',req:1},{c:'E',l:'Jenis Pelanggaran',type:'select',ref:'violationType',req:1},{c:'F',l:'Tingkat Pelanggaran',type:'select',ref:'violationLevel'},{c:'G',l:'Poin',type:'number',min:0},{c:'H',l:'Sanksi / Tindakan',cls:'two'},{c:'I',l:'Status Penyelesaian',type:'select',ref:'violationStatus'},{c:'J',l:'Penanggung Jawab'},{c:'K',l:'Tanggal Selesai',type:'date'},{c:'L',l:'Keterangan',type:'textarea',cls:'full'}]},
 sp:{icon:'📄',title:'Surat Peringatan SP 1–3',sheet:'Data SP 1-3',start:6,end:10000,primary:'C',link:'student',recordCols:['B','C','D','E','G','H','I','O'],recordLabels:['Tanggal','ID','Nama','Kelas','SP','No Surat','Jenis','Status'],intro:'Pilih siswa lalu catat SP. Kelas, program, wali, dan kontak wali dapat diambil dari Data Siswa.',fields:[
  {c:'B',l:'Tanggal Surat',type:'date',req:1},{c:'G',l:'SP Ke',type:'select',ref:'sp',req:1},{c:'H',l:'Nomor Surat'},{c:'I',l:'Jenis Pelanggaran',type:'select',ref:'violationType',req:1},{c:'J',l:'Uraian / Kronologi',type:'textarea',cls:'full',req:1},{c:'K',l:'Sanksi / Tindakan',type:'textarea',cls:'two'},{c:'N',l:'Penanggung Jawab'},{c:'O',l:'Status Tindak Lanjut',type:'select',ref:'violationStatus'},{c:'P',l:'Tanggal Selesai',type:'date'},{c:'Q',l:'Keterangan',type:'textarea',cls:'full'}]},
 keluar:{icon:'🚪',title:'Keluar / Nonaktif',sheet:'Data Keluar',start:6,end:300,primary:'D',link:'both',recordCols:['B','C','D','E','F','G','H','J','K'],recordLabels:['Tanggal','Kategori','ID','Nama','Status Saat Ini','Status Akhir','Alasan','Tindak Lanjut','Dicatat Oleh'],intro:'Catat alasan keluar/nonaktif untuk siswa/anggota, pengurus, alumni, atau kategori lain.',fields:[
  {c:'B',l:'Tanggal Efektif',type:'date',req:1},{c:'C',l:'Kategori / Posisi',type:'select',ref:'exitCategory',req:1},{c:'G',l:'Status Akhir',type:'select',opts:['Keluar','Nonaktif','Demisioner','Alumni','Lulus','Lainnya'],req:1},{c:'H',l:'Alasan Utama',type:'select',ref:'exitReason',req:1},{c:'I',l:'Detail Alasan',type:'textarea',cls:'full'},{c:'J',l:'Tindak Lanjut',type:'select',ref:'followup'},{c:'K',l:'Dicatat Oleh'},{c:'L',l:'Keterangan Otomatis',type:'textarea',cls:'full'}]}
};

function getRefOptions(key){const col=REF[key];if(!col||!docs['Referensi'])return[];const out=[];for(let r=5;r<=80;r++){const v=trim(cellText(docs['Referensi'],cellMaps['Referensi'],col+r));if(v&&!out.includes(v))out.push(v)}return out}
function moduleList(){return Object.entries(modules)}
function renderNav(){const nav=$('nav');nav.innerHTML='';for(const [k,m] of moduleList()){const b=document.createElement('button');b.className='navBtn'+(k===activeModule?' active':'');b.innerHTML=`${m.icon} ${esc(m.title)}<span>${m.special==='attendance'?'Input bulanan':'Simpan / ubah / hapus'}</span>`;b.onclick=()=>switchModule(k);nav.appendChild(b)}}
function getStudentId(r){const b=trim(cellText(docs['Data Siswa'],cellMaps['Data Siswa'],'B'+r));if(b)return b;const y=trim(cellText(docs['Data Siswa'],cellMaps['Data Siswa'],'N'+r));return y?`PN-${y}-${pad3(r-5)}`:''}
function getPengurusId(r){const b=trim(cellText(docs['Data Pengurus'],cellMaps['Data Pengurus'],'B'+r));return b||`PGR-${pad3(r-5)}`}
