function findStudentById(id){return students.find(s=>s.id===trim(id))||null}
function findPersonById(id){return students.find(s=>s.id===trim(id))||pengurusPeople.find(s=>s.id===trim(id))||null}
function coreLinkedWrite(m,row){const p=selectedPerson;if(!p)return;if(activeModule==='alumni'){writeOrCache(m.sheet,'B'+row,p.id,false,'B'+m.start);writeOrCache(m.sheet,'C'+row,p.name,false,'C'+m.start);writeOrCache(m.sheet,'D'+row,p.gender||'',false,'D'+m.start);writeOrCache(m.sheet,'E'+row,p.program||'',false,'E'+m.start);writeOrCache(m.sheet,'F'+row,p.yearMasuk||'',true,'F'+m.start);writeOrCache(m.sheet,'H'+row,p.belt||'',false,'H'+m.start)}else if(['kenaikan','prestasi','iuran','pelanggaran'].includes(activeModule)){writeOrCache(m.sheet,'C'+row,p.id,false,'C'+m.start);writeOrCache(m.sheet,'D'+row,p.name,false,'D'+m.start)}else if(activeModule==='sp'){writeOrCache(m.sheet,'C'+row,p.id,false,'C'+m.start);writeOrCache(m.sheet,'D'+row,p.name,false,'D'+m.start);writeOrCache(m.sheet,'E'+row,p.kelas||'',false,'E'+m.start);writeOrCache(m.sheet,'F'+row,p.program||'',false,'F'+m.start);writeOrCache(m.sheet,'L'+row,p.parent||'',false,'L'+m.start);writeOrCache(m.sheet,'M'+row,p.parentPhone||'',false,'M'+m.start)}else if(activeModule==='keluar'){writeOrCache(m.sheet,'D'+row,p.id,false,'D'+m.start);writeOrCache(m.sheet,'E'+row,p.name,false,'E'+m.start);writeOrCache(m.sheet,'F'+row,personStatus(p),false,'F'+m.start)}}
function refreshDerived(m,row){if(activeModule==='siswa'){writeOrCache(m.sheet,'A'+row,row-5,true,'A'+m.start);const year=getFieldValue(m.fields.find(x=>x.c==='N')||{});const id=trim(cellText(docs[m.sheet],cellMaps[m.sheet],'B'+row))||`PN-${year}-${pad3(row-5)}`;writeOrCache(m.sheet,'B'+row,id,false,'B'+m.start)}else if(activeModule==='pengurus'){writeOrCache(m.sheet,'A'+row,row-5,true,'A'+m.start);const id=trim(cellText(docs[m.sheet],cellMaps[m.sheet],'B'+row))||`PGR-${pad3(row-5)}`;writeOrCache(m.sheet,'B'+row,id,false,'B'+m.start)}else if(activeModule==='alumni'){writeOrCache(m.sheet,'A'+row,row-5,true,'A'+m.start)}else if(activeModule==='kenaikan'){writeOrCache(m.sheet,'A'+row,row-4,true,'A'+m.start);const nums=['G','H','I'].map(c=>Number(cellText(docs[m.sheet],cellMaps[m.sheet],c+row)));if(nums.every(Number.isFinite)){const sum=nums.reduce((a,b)=>a+b,0);writeOrCache(m.sheet,'J'+row,sum,true,'J'+m.start);writeOrCache(m.sheet,'K'+row,sum<75?'Tidak Lulus':'Lulus',false,'K'+m.start)}}else if(activeModule==='prestasi'||activeModule==='iuran'){writeOrCache(m.sheet,'A'+row,row-4,true,'A'+m.start)}else if(activeModule==='pelanggaran'||activeModule==='sp'||activeModule==='keluar'){writeOrCache(m.sheet,'A'+row,row-5,true,'A'+m.start)}if(activeModule==='keluar'){const date=getFieldValue(m.fields.find(x=>x.c==='B')||{}),cat=getFieldValue(m.fields.find(x=>x.c==='C')||{}),final=getFieldValue(m.fields.find(x=>x.c==='G')||{}),reason=getFieldValue(m.fields.find(x=>x.c==='H')||{}),detail=getFieldValue(m.fields.find(x=>x.c==='I')||{}),follow=getFieldValue(m.fields.find(x=>x.c==='J')||{}),by=getFieldValue(m.fields.find(x=>x.c==='K')||{});if(selectedPerson&&date&&final&&reason){const indo=new Date(date+'T00:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'});let txt=`Pada ${indo}, ${selectedPerson.name} (${cat||selectedPerson.source}) dinyatakan ${final}`;const st=personStatus(selectedPerson);if(st)txt+=` dari status ${st}`;txt+=` dengan alasan ${reason}`;if(detail)txt+=`. Detail: ${detail}`;if(follow)txt+=`. Tindak lanjut: ${follow}`;if(by)txt+=`. Dicatat oleh: ${by}`;txt+='.';writeOrCache(m.sheet,'L'+row,txt,false,'L'+m.start);const el=$('f_L');if(el)el.value=txt}}}

function newRecord(){selectedRow=0;$('rowBadge').textContent='DATA BARU';$('rowBadge').className='badge';if(modules[activeModule].special==='attendance'){clearAttendanceInputs();loadAttendanceCurrent();return}clearFormFields();if(activeModule!=='alumni'&&modules[activeModule].link){}else if(activeModule==='alumni'&&selectedPerson){prefillAlumni()}}
function prefillAlumni(){if(!selectedPerson)return;const m=modules.alumni;const map={I:'',J:'',K:'Bekerja',L:'',M:'',N:'Aktif',O:''};for(const f of m.fields)setFieldValue(f,map[f.c]??'')}
function currentModule(){return modules[activeModule]}

function peoplePool(){return currentModule().link==='both'?[...students,...pengurusPeople]:students}
function searchPeople(){const q=trim($('personSearch').value).toLowerCase(),pool=peoplePool();peopleResults=pool.filter(p=>!q||p.name.toLowerCase().includes(q)||p.id.toLowerCase().includes(q)||(p.kelas||'').toLowerCase().includes(q)||(p.position||'').toLowerCase().includes(q)).slice(0,120);const sel=$('personResults');sel.innerHTML='';peopleResults.forEach((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${p.id} | ${p.name} | ${p.source}${p.kelas?' | '+p.kelas:''}${p.position?' | '+p.position:''}`;sel.appendChild(o)});if(peopleResults.length===1){sel.selectedIndex=0;selectPerson()}}
function selectPerson(){const i=parseInt($('personResults').value,10);if(!Number.isFinite(i))return;selectedPerson=peopleResults[i];$('personCard').className='personCard';$('personCard').innerHTML=`<div class="personInfo"><b>ID</b><span>${esc(selectedPerson.id)}</span><b>Nama</b><span>${esc(selectedPerson.name)}</span><b>Sumber</b><span>${esc(selectedPerson.source)}</span><b>Status</b><span>${esc(personStatus(selectedPerson)||'-')}</span>${selectedPerson.kelas?`<b>Kelas</b><span>${esc(selectedPerson.kelas)}</span><b>Program</b><span>${esc(selectedPerson.program||'-')}</span>`:''}</div>`;if(activeModule==='alumni'&&selectedRow===0)prefillAlumni();if(activeModule==='kehadiran'){ensureAttendancePerson(false);loadAttendanceCurrent()}renderRecords(false)}
function clearPerson(){selectedPerson=null;$('personSearch').value='';$('personResults').innerHTML='';$('personCard').className='personCard hidden';searchPeople();renderRecords(false)}

function attendanceRowForPerson(){if(!selectedPerson)return 0;for(let r=4;r<=193;r++){const id=trim(cellText(docs['Kehadiran'],cellMaps['Kehadiran'],'B'+r)),nm=trim(cellText(docs['Kehadiran'],cellMaps['Kehadiran'],'C'+r));if((id&&id===selectedPerson.id)||(nm&&nm.toLowerCase()===selectedPerson.name.toLowerCase()))return r}return 0}
function ensureAttendancePerson(create){let r=attendanceRowForPerson();if(r||!create)return r;for(let x=4;x<=193;x++){if(!trim(cellText(docs['Kehadiran'],cellMaps['Kehadiran'],'C'+x))){r=x;break}}if(!r)throw new Error('Slot Kehadiran penuh.');writeOrCache('Kehadiran','A'+r,r-3,true,'A4');writeOrCache('Kehadiran','B'+r,selectedPerson.id,false,'B4');writeOrCache('Kehadiran','C'+r,selectedPerson.name,false,'C4');writeOrCache('Kehadiran','D'+r,selectedPerson.belt||'',false,'D4');return r}
function clearAttendanceInputs(){['attH','attS','attI','attA'].forEach(id=>$(id).value='');$('attDO').value=''}
function loadAttendanceCurrent(){if(activeModule!=='kehadiran')return;if(!selectedPerson){$('attCurrent').textContent='Pilih anggota terlebih dahulu.';clearAttendanceInputs();return}const r=attendanceRowForPerson(),mi=parseInt($('attMonth').value||'0',10),mo=attendanceMonths[mi];if(!r||!mo){$('attCurrent').textContent='Belum ada baris kehadiran untuk anggota ini.';clearAttendanceInputs();return}const vals=[0,1,2,3].map(i=>cellText(docs['Kehadiran'],cellMaps['Kehadiran'],ref(mo.start+i,r)));const doval=cellText(docs['Kehadiran'],cellMaps['Kehadiran'],ref(mo.start+4,r)),pct=cellText(docs['Kehadiran'],cellMaps['Kehadiran'],ref(mo.start+5,r));$('attH').value=vals[0];$('attS').value=vals[1];$('attI').value=vals[2];$('attA').value=vals[3];$('attDO').value=doval==='DO/Keluar'?'DO/Keluar':'';$('attCurrent').innerHTML=`<b>${esc(selectedPerson.name)}</b> — ${esc(mo.name)}<br>Data saat ini: Hadir <b>${esc(vals[0]||0)}</b>, Sakit <b>${esc(vals[1]||0)}</b>, Izin <b>${esc(vals[2]||0)}</b>, Tanpa Keterangan <b>${esc(vals[3]||0)}</b>, Status <b>${esc(doval||'-')}</b>, Kehadiran % <b>${esc(pct||0)}</b>.`}
function attendanceValues(){const vals=['attH','attS','attI','attA'].map(id=>{const s=trim($(id).value);return s===''?0:Number(s)});if(vals.some(v=>!Number.isFinite(v)||v<0||v>31)){alert('Nilai kehadiran harus angka 0–31.');return null}return{vals,doVal:$('attDO').value}}
